name:                MIPSFormat
version:             0.1.0.0
github:              "srithon/MIPSFormat"
license:             BSD3
author:              "Sridaran Thoniyil"
maintainer:          "sri7thon@gmail.com"
copyright:           "2022 Sridaran Thoniyil"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/srithon/MIPSFormat#readme>

dependencies:
- base >= 4.7 && < 5
- text

library:
  source-dirs: src

executables:
  MIPSFormat-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MIPSFormat

tests:
  MIPSFormat-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MIPSFormat
